blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/vote/', views.vote, name='vote'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
app_name = 'polls'

from django.urls import path
from . import views

### Generic view (class-based view)
urlpatterns=[
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results.
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/chart/', views.result_chart, name='chart'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
  question_text = models.CharField(max_length=200)
  pub_date=models.DateTimeField('date published')

  def __str__(self):
    return self.question_text

  def was_published_recently(self):
    return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

  was_published_recently.admin_order_field = 'pub_date'
  was_published_recently.boolean = True
  was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  choice_text = models.CharField(max_length=200)
  votes = models.IntegerField(default=0)

  def __str__(self):
    return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice
from django.template import loader
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
import json

### Generic View (class-based views)
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    """Return the last five published questions."""
    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


# #Create your views here.
# def index(request):
#     # return HttpResponse("Hello, world. You're at the polls index.")
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#
#     # output = ', '.join([q.question_text for q in latest_question_list])
#     # return HttpResponse(output)
#     template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))
#     return render(request, 'polls/index.html', context)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    for id_check in request.POST.getlist('choice'):
        try:
            selected_choice = question.choice_set.get(pk=id_check)
        except(KeyError, Choice.DoesNotExist):
            return render(request, 'polls/detail.html', {'question': question, 'error_message': "You didn't select a choice."})
        else:
            selected_choice.votes += 1
            selected_choice.save()

    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def make_chart_data(data_question):

    my_data = list()
    for choice in data_question.choice_set.all():
        my_dict = dict()
        my_dict['name'] = choice.choice_text
        my_dict['y'] = choice.votes
        my_data.append(my_dict)

    chart_data = [{
        'name': 'Votes',
        'colorByPoint': 'true',
        'data': my_data,
    }]

    return chart_data

def result_chart(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    chart_data = make_chart_data(question)
    dump = json.dumps(chart_data)

    chart_title = {
        'text': '투표결과 <br>' + question.question_text
    }

    dump_title = json.dumps(chart_title)

    return render(request, 'polls/chart.html', {'chart_data':dump, 'chart_title':dump_title})

polls/templates/polls/chart.html
{% extends 'base.html' %}

{% block title %} Polls Chart {% endblock %}
{% block content %}
    <div id="container" style="margin-top: 20px;"></div>

    {% load static %}
    <script type="text/javascript"> var chart_data = {{chart_data|safe}} </script>
    <script type="text/javascript"> var chart_title = {{chart_title|safe}} </script>

    <script defer src ="{% static 'polls/javascript.js' %}"></script>

    <button type="button" onclick="location.href='{% url 'polls:index' %}'" class="btn btn-outline-secondary">목록으로</button>

{% endblock %}

polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block title %} Polls Detail {% endblock %}
{% block content %}

    <h1 style="font-size: 35px">질문 : {{question.question_text}}</h1>
    <br/>
    {% if error_message %} <p> <strong>{{error_message}}</strong></p>{% endif %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type ="checkbox" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for ="choice{{forloop.counter}}">{{choice.choice_text}}</label><br><br>
    {% endfor %}
    <input type="submit" value="투표하기" class="btn btn-outline-primary">
    <button type="button" class="btn btn-outline-danger" onclick="location.href='{% url 'polls:index' %}'">뒤로가기</button>
    </form>

{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}

{% block title %} Polls index {% endblock %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ol class="list-group list-group-numbered">
    {% for question in latest_question_list %}
        <li class="list-group-item"><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
    {% endfor %}
    </ol>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

polls/templates/polls/results.html
{% extends 'base.html' %}

{% block title %} Polls detail {% endblock %}
{% block content %}
<h1>{{question.question_text}}</h1>
<ul class="list-group list-group-flush">
    {% for choice in question.choice_set.all %}
    <li class="list-group-item">{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<br/>
<button type="button" class="btn btn-outline-secondary" onclick="location.href='{% url 'polls:detail' question.id %}'">다시 투표?</button>
<button type="button" class="btn btn-outline-info" onclick="location.href='{% url 'polls:chart' question.id %}'">차트 보기</button>

{% endblock %}