blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/vote/', views.vote, name='vote'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
        default=timezone.now)
    published_date = models.DateTimeField(
        blank=True, null=True)
    like = models.IntegerField(null=True)


    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','text',)

blog/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post
from django.shortcuts import render, get_object_or_404, redirect,HttpResponseRedirect
from .forms import PostForm
from django.views.decorators.csrf import csrf_exempt


# Create your views here.

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


@csrf_exempt
def vote(request, pk):
    try:
        post = get_object_or_404(Post, pk=pk)
    except(KeyError, Post.DoesNotExist):
        return render(request, 'blog/post_detail.html', {'post': post, 'error_message': "You didn't select a choice."})
    else:
        post.like += 1
        post.save()

    return render(request, 'blog/post_detail.html', {'post': post})

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <title>Title</title>
</head>
<body>

<div class="page-header">
  {% if user.is_authenticated %}
  <a href="{% url 'blog:post_new' %}" class="top-menu">
    <span class="glyphicon glyphicon-plus"></span></a>
  {% endif %}
    <h1><a href="{% url 'blog:post_list' %}">HYWU Blog</a></h1>
</div>

<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
              {% for post in posts %}
                <div class="post">
                  <div class="date">
                    {{ post.published_date }}
                  </div>
                  <h1><a href="">{{ post.title }}</a></h1>
                  <p>{{ post.text|linebreaksbr }}</p>
                </div>
              {% endfor %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

blog/templates/blog/post_detail.html
{#{% extends 'blog/base.html' %}#}
{% extends 'base.html' %}

{% block content %}
    {% load static %}
{#    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">#}
{#    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">#}
{#    <div class="page-header">#}
{#      {% if user.is_authenticated %}#}
{#      <a href="{% url 'blog:post_new' %}" class="top-menu">#}
{#        <span class="glyphicon glyphicon-plus"></span></a>#}
{#      {% endif %}#}
{#        <h1><a href="{% url 'blog:post_list' %}">Kimjy01's Blog</a></h1>#}
{#    </div>#}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}

        <h1>제목 : {{ post.title }}</h1>
        <hr>
        <p>내용 : {{ post.text|linebreaksbr }}</p>
        <hr>
        <form action="{% url 'blog:vote' pk=post.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="좋아요" class="btn btn-outline-danger" id="count">
            <button type="button" class="btn btn-outline-danger" id="like" disabled>{{ post.like }}</button>
        </form>
        <br>
        <br>
        {% if user.is_authenticated %}
            <a class="btn btn-outline-info" href="{% url 'blog:post_edit' pk=post.pk %}">수정하기</a>
        {% endif %}
        <button type="button" class="btn btn-outline-secondary" onclick="location.href='{% url 'blog:post_list' %}'">뒤로가기</button>
    </div>

    <script>

    // 'request'라는 id를 가진 버튼 클릭 시 실행.
    $("#count").click(function(){

            // json 형식으로 데이터 set
            var params = {

            }

            // ajax 통신
            $.ajax({
                type : "POST",            // HTTP method type(GET, POST) 형식이다.
                url : "/test/ajax",      // 컨트롤러에서 대기중인 URL 주소이다.
                data : params,            // Json 형식의 데이터이다.
                success : function(res){ // 비동기통신의 성공일경우 success콜백으로 들어옵니다. 'res'는 응답받은 데이터이다.
                    // 응답코드 > 0000
                    alert(res.code);
                },
                error : function(XMLHttpRequest, textStatus, errorThrown){ // 비동기 통신이 실패할경우 error 콜백으로 들어옵니다.
                    alert("통신 실패.")
                }
            });
        });

    </script>
{% endblock %}

blog/templates/blog/post_edit.html
{#{% extends 'blog/base.html' %}#}
{% extends 'base.html' %}

{% block content %}
    {% load static %}
{#    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">#}
{#    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">#}
{#    <div class="page-header">#}
{#      {% if user.is_authenticated %}#}
{#      <a href="{% url 'blog:post_new' %}" class="top-menu">#}
{#        <span class="glyphicon glyphicon-plus"></span></a>#}
{#      {% endif %}#}
{#        <h1><a href="{% url 'blog:post_list' %}">HYWU Blog</a></h1>#}
{#    </div>#}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-secondary">저장하기</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{#{% extends 'blog/base.html' %}#}
{% extends 'base.html' %}

{% block content %}
    <br>
    <div class="page-header" style="display: flex; justify-content: space-between; flex-direction: row-reverse; align-items: center">
      {% if user.is_authenticated %}
      <a class="btn btn-outline-primary"href="{% url 'blog:post_new' %}" class="top-menu">추가하기</a>
      {% endif %}
    <h1><a href="{% url 'blog:post_list' %}">Kimjy01's Blog</a></h1>
    </div>
    <br>
    <hr>
    {% for post in posts %}
    <div class="post">
        <div class="date">
            <p>published:{{post.published_date}}</p>
        </div>
        <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
    <hr>
    {% endfor %}
{% endblock %}